services:
  db:
    image: postgres:17
    container_name: litcircle_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - litcircle_postgres_data:/var/lib/postgresql/data

volumes:
  litcircle_postgres_data:
