# Generated by Django 4.2.23 on 2025-08-29 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('circles', '0001_initial'),
        ('users', '0002_rename_avatar_url_profile_social_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_books_id', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('authors', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_books_id', models.CharField(max_length=100)),
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='circles.circle')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='CircleReadBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_books', to='circles.circle')),
            ],
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('circle', 'google_books_id', 'profile'), name='unique_vote'),
        ),
        migrations.AddConstraint(
            model_name='circlereadbook',
            constraint=models.UniqueConstraint(fields=('circle', 'book'), name='unique_circle_book'),
        ),
    ]
